// <auto-generated />
namespace Boonbook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Boon_OptionalExpenditureDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Boon_OptionalExpenditureDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201508112047273_Boon_OptionalExpenditureDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
